version: 2
jobs:
  release-snapshot:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm i
      - run:
          name: Deploy
          command: |
            export NPM_TOKEN=${SNAPSHOT_NPM_TOKEN}
            npm config set ${NPM_PACKAGE_SCOPE}:registry ${NPM_SNAPSHOT_REPO}
            npm run build
            npx semantic-release
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm i
      - run: echo "Running release job"
      - run: npm run build
      - run:
          name: Deploy
          command: npx semantic-release

workflows:
  version: 2
  release:
    jobs:
      - release-snapshot:
          context: Mark
          filters:
            branches:
              only:
                - /^feature\/.+$/
      - release:
          context: Mark
          filters:
            branches:
              only:
                - main